version: '3.1'

services:
  api:
    image: url_shortener:local
    env_file:
      - .env
    ports:
      - 5002:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGUSER: url_shortener
      POSTGRES_PASSWORD: password
    volumes:
      -  pgdata:/var/lib/postgresql/data
      -  ./bin/local-init.sql:/docker-entrypoint-initdb.d/local-init.sql
    ports:
      - 5001:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: