version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USE: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      -  pgdata:/var/lib/postgresql/data
      -  ./bin/local-init.sql:/docker-entrypoint-initdb.d/local-init.sql
    ports:
      - 5001:5432
volumes:
  pgdata: